// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvents = `-- name: InsertEvents :exec
INSERT INTO events (aggregate_id, event_type, payload, version, occurred_at)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::jsonb[]),
    unnest($4::bigint[]),
    unnest($5::timestamptz[])
`

type InsertEventsParams struct {
	AggregateIds []pgtype.UUID
	EventTypes   []string
	Payloads     [][]byte
	Versions     []int64
	OccurredAts  []pgtype.Timestamptz
}

// Inserts a batch of events for one or more aggregates.
// The UNIQUE(aggregate_id, version) constraint enforces optimistic concurrency:
// if another writer already committed the same version, this will error.
func (q *Queries) InsertEvents(ctx context.Context, db DBTX, arg *InsertEventsParams) error {
	_, err := db.Exec(ctx, insertEvents,
		arg.AggregateIds,
		arg.EventTypes,
		arg.Payloads,
		arg.Versions,
		arg.OccurredAts,
	)
	return err
}

const loadEventsByAggregateID = `-- name: LoadEventsByAggregateID :many
SELECT id, aggregate_id, event_type, payload, version, occurred_at
FROM   events
WHERE  aggregate_id = $1
ORDER  BY version ASC
`

func (q *Queries) LoadEventsByAggregateID(ctx context.Context, db DBTX, aggregateID pgtype.UUID) ([]*Event, error) {
	rows, err := db.Query(ctx, loadEventsByAggregateID, aggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Version,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
