// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID
	AggregateID pgtype.UUID
	EventType   string
	Payload     []byte
	Version     int64
	OccurredAt  pgtype.Timestamptz
}

type WalletView struct {
	ID        pgtype.UUID
	OwnerID   string
	Balance   pgtype.Numeric
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
