// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_views.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWalletView = `-- name: GetWalletView :one
SELECT id, owner_id, balance, currency, status, created_at, updated_at
FROM   wallet_views
WHERE  id = $1
`

func (q *Queries) GetWalletView(ctx context.Context, db DBTX, id pgtype.UUID) (*WalletView, error) {
	row := db.QueryRow(ctx, getWalletView, id)
	var i WalletView
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listWalletViewsByOwner = `-- name: ListWalletViewsByOwner :many
SELECT id, owner_id, balance, currency, status, created_at, updated_at
FROM   wallet_views
WHERE  owner_id = $1
ORDER  BY created_at ASC
`

func (q *Queries) ListWalletViewsByOwner(ctx context.Context, db DBTX, ownerID string) ([]*WalletView, error) {
	rows, err := db.Query(ctx, listWalletViewsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WalletView
	for rows.Next() {
		var i WalletView
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Balance,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletViewBalance = `-- name: UpdateWalletViewBalance :exec
UPDATE wallet_views
SET balance = $1, updated_at = $2
WHERE id = $3
`

type UpdateWalletViewBalanceParams struct {
	Balance   pgtype.Numeric
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateWalletViewBalance(ctx context.Context, db DBTX, arg *UpdateWalletViewBalanceParams) error {
	_, err := db.Exec(ctx, updateWalletViewBalance, arg.Balance, arg.UpdatedAt, arg.ID)
	return err
}

const updateWalletViewStatus = `-- name: UpdateWalletViewStatus :exec
UPDATE wallet_views
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateWalletViewStatusParams struct {
	Status    string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateWalletViewStatus(ctx context.Context, db DBTX, arg *UpdateWalletViewStatusParams) error {
	_, err := db.Exec(ctx, updateWalletViewStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertWalletView = `-- name: UpsertWalletView :exec
INSERT INTO wallet_views (id, owner_id, balance, currency, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    balance    = EXCLUDED.balance,
    currency   = EXCLUDED.currency,
    status     = EXCLUDED.status,
    updated_at = EXCLUDED.updated_at
`

type UpsertWalletViewParams struct {
	ID        pgtype.UUID
	OwnerID   string
	Balance   pgtype.Numeric
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertWalletView(ctx context.Context, db DBTX, arg *UpsertWalletViewParams) error {
	_, err := db.Exec(ctx, upsertWalletView,
		arg.ID,
		arg.OwnerID,
		arg.Balance,
		arg.Currency,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
